In [1]:
# Machine Learnig:
# c/ c++

# Numpy : array

# numpy: ndarrays

a = [1, 2, 3, 4]

In [2]:
type(a)

list

In [3]:
# ndarray
import numpy as np

arr = np.array(12)

In [4]:
arr.ndim

0

In [5]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [6]:
arr.ndim

2

In [7]:
arr = np.array([[[1, 2, 3], [5, 6, 7]], [[8, 9, 10], [11, 12, 13]]])
arr.ndim

3

In [8]:
arr = np.array([1, 2, 3, 4, 5])


In [9]:
arr.shape

(5,)

In [10]:
arr[4] + arr[3]

9

In [11]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
# arr[0, 2]
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
arr.shape

(2, 5)

In [13]:
arr = np.array([[[1, 2, 3], [5, 6, 7]], [[8, 9, 10], [11, 12, 13]]])
arr[0, 1, 2]

7

In [14]:
arr.shape

(2, 2, 3)

In [15]:
a = np.array([1, 2, 3, 4, 5, 6])

a.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a.info

AttributeError: 'numpy.ndarray' object has no attribute 'info'

In [17]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([3, 4, 5])

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 3, 4, 5])

In [18]:
a = np.array([1, 6, 2, 3,6,  4, 5, 6])
np.where(a == 6)

(array([1, 4, 7]),)

In [19]:
# pandas

# 1) to analize data
# 2) Cleaning data
# 3) Visulize data
# 4) retrive data
# ...

In [20]:
import pandas as pd

In [21]:
# 1) Series
# 2) DataFrame

data = pd.read_csv("data.csv")

In [22]:
data

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [23]:
a = [1, 2, 3, 4]

df = pd.Series(a, index = [21, 'b', 'c', 'd'])

In [24]:
df

21    1
b     2
c     3
d     4
dtype: int64

In [25]:
df[3]

KeyError: 3

In [ ]:
# data.to_string()

In [ ]:
data.head(20)

In [26]:
data.tail()

Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [27]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  169 non-null    int64  
 1   Pulse     169 non-null    int64  
 2   Maxpulse  169 non-null    int64  
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB


In [28]:
xyz = {
    "name" : ["kris", "moris", "raiin"],
    "age" : [11, 22, 23]
}

In [29]:
xyz

{'name': ['kris', 'moris', 'raiin'], 'age': [11, 22, 23]}

In [30]:
x = pd.DataFrame(xyz)

In [31]:
x

name  age
0   kris   11
1  moris   22
2  raiin   23

In [32]:
x.iloc['age']

TypeError: Cannot index by location index with a non-integer key

In [ ]:
data

In [33]:
xyz = data.dropna()

In [34]:
xyz

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[164 rows x 4 columns]

In [35]:
data['Calories'].fillna(120.0, inplace=True)


In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  169 non-null    int64  
 1   Pulse     169 non-null    int64  
 2   Maxpulse  169 non-null    int64  
 3   Calories  169 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB


In [38]:
data.corr()

Duration     Pulse  Maxpulse  Calories
Duration  1.000000 -0.155408  0.009403  0.915805
Pulse    -0.155408  1.000000  0.786535  0.038556
Maxpulse  0.009403  0.786535  1.000000  0.212613
Calories  0.915805  0.038556  0.212613  1.000000