In [1]:
# Numpy : 

In [2]:
import numpy as np

In [7]:
arr = np.array([[[12, 34, 56, 100], [45, 34, 45, 100]], [[45, 34, 56, 23], [67, 45, 34, 2]]])

In [8]:
arr.ndim

3

In [9]:
arr

array([[[ 12,  34,  56, 100],
        [ 45,  34,  45, 100]],

       [[ 45,  34,  56,  23],
        [ 67,  45,  34,   2]]])

In [10]:
# list

In [11]:
# indexing with 1 d ndarray

In [13]:
x = np.array([34, 56, 34, 23, 45, 65, 45, 78, 34, 100])

In [14]:
# objname[indexnumber]

In [15]:
x[3]

23

In [16]:
x[7]

78

In [17]:
# negtive indexing.....

In [18]:
x[-2]

34

In [19]:
# slicingggggg:

In [20]:
x = np.array([34, 56, 34, 23, 45, 65, 45, 78, 34, 100])

In [ ]:
# objename[start : end : increment]

# default :
# start : 0
# end : n - 1
# increment : 1

In [21]:
x[1 : 6 : 1]

array([56, 34, 23, 45, 65])

In [23]:
x[3 : 9 : 1]

array([23, 45, 65, 45, 78, 34])

In [24]:
x[ : 7]

array([34, 56, 34, 23, 45, 65])

In [25]:
x = np.array([34, 56, 34, 23, 45, 65, 45, 78, 34, 100])

In [27]:
x[2 : : 2]

array([34, 45, 45, 34])

In [28]:
x[: : -1]

array([100,  34,  78,  45,  65,  45,  23,  34,  56,  34])

## extract data from 2d

In [34]:
xy = np.array([[34, 56, 34, 2, 45, 23, 45, 23], [45, 23, 45, 67, 34, 23, 45, 23]])

In [35]:
xy

array([[34, 56, 34,  2, 45, 23, 45, 23],
       [45, 23, 45, 67, 34, 23, 45, 23]])

In [38]:
xy[1][3]

67

In [41]:
xy[0][3]

2

In [43]:
xy[1][1 : 6]

array([23, 45, 67, 34, 23])

In [44]:
arr = np.array([[[12, 34, 56, 100], [45, 34, 45, 100]], [[45, 34, 56, 23], [67, 45, 34, 2]]])

In [48]:
arr[1][1][-1]

2

In [59]:
arr[1][0][-1]

23

In [60]:
x = np.array([34, 56, 34, 23, 45, 65, 45, 78, 34, 100])

In [61]:
x[4], x[-1]

(45, 100)

In [72]:
zx = np.array([[[[[[34, 56, 34]]]]]])

In [65]:
zx.ndim

6

In [74]:
zx[0][0][0][0][0][1]

56

In [76]:
zx[6][0][3]

IndexError: index 6 is out of bounds for axis 0 with size 1

In [89]:
x = np.array([[[[12, 34, 5], [56, 34, 2]], [[56, 45, 34], [45, 45, 23]]], [[[12, 34, 5], [8, 34, 2]], [[56, 45, 34], [45, 45, 23]]]])

In [90]:
x.ndim

4

In [96]:
x[1][0][1][0]

8

In [97]:
# Ndarray Modification...

In [98]:
# 1) elements replace

In [99]:
x = np.array([34, 56, 34, 23, 45, 65, 45, 78, 34, 100])

In [100]:
# objname[indexnumber] = newelement

In [101]:
x[5] = 700

In [102]:
x

array([ 34,  56,  34,  23,  45, 700,  45,  78,  34, 100])

In [103]:
x = np.array([34, 56, 34, 23, 45, 65, 45, 78, 34, 100])

In [104]:
mych = [0, 3, -1]

ele = [100, 200, 300]

In [105]:
x[mych] = ele

In [106]:
x

array([100,  56,  34, 200,  45,  65,  45,  78,  34, 300])

In [107]:
# append()

In [108]:
x = np.array([34, 56, 34, 23, 45, 65, 45, 78, 34, 100])

In [109]:
# append()

In [110]:
# np.append(objename, elmet)

In [113]:
y = np.append(x, 5000)

In [114]:
y

array([  34,   56,   34,   23,   45,   65,   45,   78,   34,  100, 5000])

In [117]:
y = np.append(x, [1, 2, 1, 2, 3, 1, 2, 3])

In [118]:
y

array([ 34,  56,  34,  23,  45,  65,  45,  78,  34, 100,   1,   2,   1,
         2,   3,   1,   2,   3])

In [119]:
# insert()

In [120]:
x = np.array([34, 56, 34, 23, 45, 65, 45, 78, 34, 100])

In [122]:
# np.insert(objename, indexnumber, elmentname)

In [123]:
np.insert(x, 1, 20)

array([ 34,  20,  56,  34,  23,  45,  65,  45,  78,  34, 100])

In [124]:
# delete:

In [125]:
x = np.array([34, 56, 34, 23, 45, 65, 45, 78, 34, 100])

In [126]:
# np.delete(objname, elmet index number)

In [129]:
np.delete(x, 4)

array([ 34,  56,  34,  23,  65,  45,  78,  34, 100])