In [1]:
# Numpy Reshape::

In [2]:
import numpy as np

In [3]:
x = np.array([12, 56, 4, 56, 34, 23, 56, 23, 1, 34, 56, 23, 100, 90])

In [4]:
len(x)

14

In [5]:
# [12, 34, 5, 34, 23, 45]

## 1D to 2D ndarray:

In [9]:
x = np.array([12, 56, 4, 56, 34, 23, 56, 23, 1, 34, 56, 23, 100, 90, 45])

In [11]:
x.reshape(5, 3)

array([[ 12,  56,   4],
       [ 56,  34,  23],
       [ 56,  23,   1],
       [ 34,  56,  23],
       [100,  90,  45]])

In [15]:
x = np.array([12, 56, 4, 56, 34, 23, 56, 23, 1, 34, 56, 23, 100, 90, 45, 34, 56, 34])

In [17]:
len(x)

18

In [16]:
x.reshape(3, 3, 2)

array([[[ 12,  56],
        [  4,  56],
        [ 34,  23]],

       [[ 56,  23],
        [  1,  34],
        [ 56,  23]],

       [[100,  90],
        [ 45,  34],
        [ 56,  34]]])

In [18]:
x = np.array([12, 56, 4, 56, 34, 23, 56, 23, 1, 34, 56, 23, 100, 90, 45, 34, 56, 34])

In [20]:
x.reshape(3, -1)

array([[ 12,  56,   4,  56,  34,  23],
       [ 56,  23,   1,  34,  56,  23],
       [100,  90,  45,  34,  56,  34]])

In [23]:
x = np.array([12, 56, 4, 56, 34, 23, 56, 23, 1, 34, 56, 23, 100, 90, 45, 34, 56, 34, 34])

In [26]:
# x.reshape(-1, 4)

In [27]:
x = np.array([[34, 56, 34, 2], [56, 78, 45, 34]])

In [29]:
x.ndim

2

In [31]:
x.reshape(-1)

array([34, 56, 34,  2, 56, 78, 45, 34])

In [32]:
x = np.array([12, 56, 4, 56, 34, 23, 56, 23, 1, 34, 56, 23, 100, 90, 45, 34, 56, 34])

In [33]:
x.ndim

1

In [34]:
len(x)

18

In [ ]:
3, 3, 2   ---- 2, 3, 3

In [35]:
x.reshape(2, 3, 3)

array([[[ 12,  56,   4],
        [ 56,  34,  23],
        [ 56,  23,   1]],

       [[ 34,  56,  23],
        [100,  90,  45],
        [ 34,  56,  34]]])

In [36]:
# unique: 

In [37]:
x = np.array([34, 5, 34, 23, 34, 23, 34, 56, 34, 45, 6, 89, 45, 34, 45, 34, 3, 23, 10])

In [38]:
np.unique(x)

array([ 3,  5,  6, 10, 23, 34, 45, 56, 89])

In [39]:
# zx = {34, 5, 34, 23, 34, 23, 34, 56, 34, 45, 6, 89, 45, 34, 45, 34, 3, 23, 10}

In [41]:
# zx

In [42]:
# arange() ------ range()

In [43]:
zx = np.arange(1, 21, 1)

In [44]:
zx

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [45]:
# default:
#     start : 0
#     end : n - 1
#     incremnt  : 1

In [48]:
zx = np.arange(1, 21, 2)

In [49]:
zx

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [50]:
# zeros()

In [ ]:
np.zeros

In [51]:
help(np.append)

Help on _ArrayFunctionDispatcher in module numpy:

append(arr, values, axis=None)
    Append values to the end of an array.

    Parameters
    ----------
    arr : array_like
        Values are appended to a copy of this array.
    values : array_like
        These values are appended to a copy of `arr`.  It must be of the
        correct shape (the same shape as `arr`, excluding `axis`).  If
        `axis` is not specified, `values` can be any shape and will be
        flattened before use.
    axis : int, optional
        The axis along which `values` are appended.  If `axis` is not
        given, both `arr` and `values` are flattened before use.

    Returns
    -------
    append : ndarray
        A copy of `arr` with `values` appended to `axis`.  Note that
        `append` does not occur in-place: a new array is allocated and
        filled.  If `axis` is None, `out` is a flattened array.

    See Also
    --------
    insert : Insert elements into an array.
    delete : Delete e

In [65]:
zx = np.zeros((3, 4))

In [66]:
zx

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [67]:
x = np.ones((2, 5))

In [68]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [69]:
# random

In [70]:
# import random

from numpy import random

In [81]:
x = random.randint(50, size = (5, 3))

In [82]:
x

array([[24, 17, 30],
       [40, 17, 10],
       [33, 24, 17],
       [25, 14, 41],
       [16, 43, 35]])

In [84]:
x.ndim

2

In [86]:
x.shape

(5, 3)

In [ ]:
# rand --> 0, 1

In [94]:
random.rand(3, 4)

array([[0.76394477, 0.91639173, 0.32900276, 0.42576844],
       [0.17882289, 0.15197679, 0.33142555, 0.13087015],
       [0.11041364, 0.91211894, 0.04227667, 0.77789098]])

In [95]:
# choice() --> 

In [101]:
random.choice([34, 45, 23, 45, 23, 67, 78])

78

In [103]:
random.choice([34, 45, 23, 45, 23, 67, 78], size = (4, 8))

array([[67, 78, 34, 45, 23, 34, 67, 45],
       [34, 78, 78, 34, 34, 45, 23, 67],
       [45, 45, 34, 78, 45, 45, 67, 67],
       [23, 78, 45, 34, 78, 23, 34, 45]])

In [105]:
help(random.choice)

Help on built-in function choice:

choice(...) method of numpy.random.mtrand.RandomState instance
    choice(a, size=None, replace=True, p=None)

    Generates a random sample from a given 1-D array

    .. versionadded:: 1.7.0

    .. note::
        New code should use the `~numpy.random.Generator.choice`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    a : 1-D array-like or int
        If an ndarray, a random sample is generated from its elements.
        If an int, the random sample is generated as if it were ``np.arange(a)``
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    replace : boolean, optional
        Whether the sample is with or without replacement. Default is True,
        meaning that a value of ``