In [1]:
# Numpy
# Pandas
# matplotlib

In [2]:
# Numpy -->

# arrays

# zx = [12, 45, 23, "heloo", "car"]

# Hittrogenoius

In [ ]:
Numpy : Numarical Python

2005 ------> Travis Oliphant


Numpy vs list

# [10, 34, ..........

numpy:

python : 70%
c/c++ : 30%

50X



In [3]:
!pip install numpy

DEPRECATION: textract 1.6.5 has a non-standard dependency specifier extract-msg<=0.29.*. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of textract or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063


In [6]:
import numpy as np

In [8]:
# arrays....:

In [ ]:
ndarrays : when we create ab object in numpy with the help array method, that object is called ndarray

In [9]:
arr = np.array(100)

In [10]:
type(arr)

numpy.ndarray

In [11]:
# arrays:

In [12]:
# ndim-----> hepl us to get the demssion of na ndarray

In [13]:
arr.ndim

0

### 1 -d ndarray

In [14]:
xyz = np.array([12, 45, 67, 34, 100, 90])

In [15]:
xyz

array([ 12,  45,  67,  34, 100,  90])

In [16]:
xyz.ndim

1

## 2d arrays

In [23]:
x = np.array([[12, 34, 56, 78], [56, 78, 45, 34], [56, 78, 45, 23]])

In [24]:
x

array([[12, 34, 56, 78],
       [56, 78, 45, 34],
       [56, 78, 45, 23]])

In [22]:
x.ndim

2

### 3d ndarray

In [31]:
y = np.array([[[2, 3, 4, 5], [4, 5, 2, 3]], [[34, 45, 23, 12], [45, 78, 34, 23]]])

In [32]:
y

array([[[ 2,  3,  4,  5],
        [ 4,  5,  2,  3]],

       [[34, 45, 23, 12],
        [45, 78, 34, 23]]])

In [33]:
y.ndim

3

In [34]:
xyz = np.array([[[[[[45]]]]]])

In [35]:
xyz.ndim

6

In [ ]:
5D

In [ ]:
ndaray
ndim